import turtle

def main():

    kevin = turtle.Turtle ()
    kevin.hideturtle()
    kevin.color("red")
    kevin.speed(10)
    kevin.pensize(8)
    kevin.penup()
    kevin.setpos(-175,75)
    kevin.pendown()
    kevin.speed(1)
    kevin.setpos(-125,75)
    kevin.speed(8)
    kevin.setpos(-150,75)
    kevin.speed(1)
    kevin.setpos(-150,10)
#End of First "T"
#Start of "U"
    kevin.color("orange")
    kevin.speed(10)
    kevin.penup()
    kevin.setpos(-100,75)
    kevin.pendown()
    kevin.speed(1)
    kevin.setpos(-100,10)
    kevin.setpos(-60,10)
    kevin.setpos(-60,75)
    #End of "U"
    #Start of "R"
    kevin.color("yellow")
    kevin.penup()
    kevin.speed(10)
    kevin.setpos(-30,10)
    kevin.pendown()
    kevin.speed(1)
    kevin.setpos(-30,75)
    kevin.setpos(0,75)
    kevin.setpos(0,45)
    kevin.setpos(7,10)
    kevin.speed(8)
    kevin.setpos(0,45)
    kevin.speed(1)
    kevin.setpos(-30,45)
    #End of "R"
    #Start of Second "T"
    kevin.color("green")
    kevin.speed(10)
    kevin.penup()
    kevin.setpos(25,75)
    kevin.pendown()
    kevin.speed(1)
    kevin.setpos(75,75)
    kevin.speed(8)
    kevin.setpos(50,75)
    kevin.speed(1)
    kevin.setpos(50,10)
    #End of Second "T"
    #Start of "L"
    kevin.color("blue")
    kevin.speed(10)
    kevin.penup()
    kevin.setpos(105,75)
    kevin.pendown()
    kevin.speed(1)
    kevin.setpos(105,10)
    kevin.setpos(135,10)
    #End of "L"
    #Start of "E"
    kevin.color("indigo")
    kevin.speed(8)
    kevin.penup()
    kevin.setpos(155,75)
    kevin.pendown()
    kevin.speed(1)
    kevin.setpos(155,10)
    kevin.speed(10)
    kevin.setpos(155,75)
    kevin.speed(1)
    kevin.setpos(190,75)
    kevin.penup()
    kevin.speed(8)
    kevin.setpos(155,44)
    kevin.pendown()
    kevin.speed(1)
    kevin.setpos(190,44)
    kevin.penup()
    kevin.speed(8)
    kevin.setpos(155,10)
    kevin.pendown()
    kevin.speed(1)
    kevin.setpos(190,10)
    #End of "E"
    kevin.color("violet")
    kevin.pensize(1)
    kevin.speed(8)
    kevin.penup()
    kevin.setpos(10,-130)
    kevin.pendown()
    kevin.showturtle()
    kevin.shape("turtle")
    kevin.speed(3)
    kevin.circle(20)
    kevin.circle(25)
    kevin.circle(30)
    kevin.circle(35)
    kevin.circle(40)
    kevin.circle(45)
    kevin.circle(50)
    kevin.circle(55)
    kevin.color("black")
    kevin.penup()
    kevin.hideturtle()
    kevin.speed(10)
    kevin.setpos(-175,85)
    kevin.showturtle()
    kevin.speed(1)
    kevin.setpos(190,85)
    kevin.setpos(190,0)
    kevin.setpos(-175,0)
    kevin.setpos(-175,85)
    kevin.hideturtle()
    kevin.speed(5)
    kevin.setpos(-1000, -1000)

    kevin.pensize(40)
    kevin.shape("square")
    kevin.speed(6)
    kevin.setpos(-190,75)
    kevin.pendown()
    kevin.speed(2)
    kevin.color("white")
    kevin.setpos(190,75)

    kevin.speed(6)
    kevin.penup()
    kevin.setpos(190,35)
    kevin.pendown()
    kevin.speed(2)
    kevin.setpos(-190,35)

    kevin.speed(6)
    kevin.penup()
    kevin.setpos(-190,-5)
    kevin.pendown()
    kevin.speed(2)
    kevin.setpos(190,-5)

    kevin.speed(10)
    kevin.penup()
    kevin.setpos(190,-45)
    kevin.pendown()
    kevin.speed(2)
    kevin.setpos(-190,-45)

    kevin.speed(10)
    kevin.penup()
    kevin.setpos(-190,-85)
    kevin.pendown()
    kevin.speed(2)
    kevin.setpos(190,-85)

    kevin.speed(10)
    kevin.penup()
    kevin.setpos(190,-125)
    kevin.pendown()
    kevin.speed(2)
    kevin.setpos(-190,-125)

    kevin.speed(10)
    kevin.penup()
    kevin.setpos(-190,-165)
    kevin.pendown()
    kevin.speed(2)
    kevin.setpos(190,-165)

    bob = turtle.Turtle()
    bob.hideturtle()
    bob.penup()
    bob.setpos(0,-128)
    bob.pendown()
    bob.speed(7)
    bob.color("purple")
    bob.shape("square")
    bob.begin_fill()
    bob.circle(90)
    bob.end_fill()
    bob.circle(100)
    bob.color("aqua")
    bob.circle(105)
    bob.color("purple")
    bob.circle(110)
    bob.color("aqua")
    bob.circle(115)
    bob.color("purple")
    bob.circle(120)
    bob.color("aqua")
    bob.circle(125)
    bob.color("purple")
    bob.circle(130)
    bob.color("aqua")
    bob.circle(135)
    bob.color("purple")
    bob.circle(140)
    bob.color("aqua")
    bob.circle(145)
    bob.color("purple")
    bob.circle(150)
    bob.color("aqua")
    bob.circle(155)
    bob.color("purple")
    bob.circle(160)
    bob.pensize(6)
    bob.setpos(0,177)
    bob.showturtle()

    steve = turtle.Turtle()
    steve.color("purple")
    steve.setpos(0,-128)
    steve.speed(4)
    steve.color("aqua")
    steve.hideturtle()
    steve.shape("square")
    steve.circle(10)
    steve.circle(15)
    steve.circle(20)
    steve.circle(25)
    steve.speed(6)
    steve.circle(30)
    steve.circle(35)
    steve.circle(40)
    steve.circle(45)
    steve.speed(7)
    steve.circle(50)
    steve.circle(55)
    steve.circle(60)
    steve.circle(65)
    steve.speed(8)
    steve.circle(70)
    steve.circle(75)
    steve.circle(80)
    steve.circle(85)

main()

turtle.done()